<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>donasi_select</name>
   <tag></tag>
   <elementGuidId>e1b542c7-2e4f-4e4f-a390-36798ff8b5da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='template_horizontal-portrait-card-slider']/div[2]/div/a[2]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;template_horizontal-portrait-card-slider&quot;)/div[@class=&quot;style__TemplateSliderContainer-sc-7v6i17-0 ldRtqq&quot;]/div[@class=&quot;style__ContainerSlider-sc-7v6i17-1 iLxHxd&quot;]/a[@class=&quot;style__CardLink-sc-7v6i17-2 gSOqSI&quot;]/div[@class=&quot;style__CardContainer-sc-1ezzaok-0 dLdGTW&quot;]/div[@class=&quot;style__GridContainer-sc-1w9zwrq-0 jSFrGK&quot;][count(. | //*[@class = 'style__GridContainer-sc-1w9zwrq-0 jSFrGK' and (text() = 'Renovasi Mushola Darurat Tahfidz Putri ParepareYayasan Baitul Maal HidayatullahTerkumpulRp 50.209.730' or . = 'Renovasi Mushola Darurat Tahfidz Putri ParepareYayasan Baitul Maal HidayatullahTerkumpulRp 50.209.730')]) = count(//*[@class = 'style__GridContainer-sc-1w9zwrq-0 jSFrGK' and (text() = 'Renovasi Mushola Darurat Tahfidz Putri ParepareYayasan Baitul Maal HidayatullahTerkumpulRp 50.209.730' or . = 'Renovasi Mushola Darurat Tahfidz Putri ParepareYayasan Baitul Maal HidayatullahTerkumpulRp 50.209.730')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__GridContainer-sc-1w9zwrq-0 jSFrGK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Renovasi Mushola Darurat Tahfidz Putri ParepareYayasan Baitul Maal HidayatullahTerkumpulRp 50.209.730</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template_horizontal-portrait-card-slider&quot;)/div[@class=&quot;style__TemplateSliderContainer-sc-7v6i17-0 ldRtqq&quot;]/div[@class=&quot;style__ContainerSlider-sc-7v6i17-1 iLxHxd&quot;]/a[@class=&quot;style__CardLink-sc-7v6i17-2 gSOqSI&quot;]/div[@class=&quot;style__CardContainer-sc-1ezzaok-0 dLdGTW&quot;]/div[@class=&quot;style__GridContainer-sc-1w9zwrq-0 jSFrGK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='template_horizontal-portrait-card-slider']/div[2]/div/a[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terkumpul'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
